//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int book_id { get; set; }
        public string title { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> genre_id { get; set; }
        public int price { get; set; }
        public System.DateTime publication_year { get; set; }
    
        public virtual author author { get; set; }
    }
}
